Repository MoonHighway/clam-graphql-api, pull requests merged in 2018-10, with the labels that each got.

#31 Incorporates JEST Testing
  .gitignore
  .travis.yml
  package-lock.json
  package.json
  src/index.js
  src/index.test.js
  src/resolvers/index.js
  src/resolvers/index.test.js
  src/resolvers/ready.js
  src/resolvers/ready.test.js
  src/server.js
  src/server.test.js
Labels: continuous-delivery, unit-testing

#32 2 cucumber
  features/ready.feature
  features/step_definitions/GraphQL_Query_Steps.js
  features/support/hooks.js
  features/support/server.js
  features/support/world.js
  package-lock.json
  package.json
  src/server.js
Labels: continuous-delivery, integration-testing

#33 Adds Prettier Config
  .prettierrc.yaml
  README.MD
  features/support/hooks.js
  package-lock.json
  package.json
  src/index.js
  src/index.test.js
  src/server.js
  src/server.test.js
  webpack.config.js
Labels: continuous-delivery

#35 removes NODE_ENV checks
  CONTRIBUTING.md
  src/server.js
  src/server.test.js
Labels: apollo-engine

#39 Temporary fixes issue
  src/server.js
Labels: tooling

#40 13 counselor queries
  .gitignore
  .prettierignore
  .travis.yml
  CONTRIBUTING.md
  README.MD
  features/counselors.feature
  features/ready.feature
  features/step_definitions/GraphQL_Query_Steps.js
  features/support/server.js
  package-lock.json
  src/data/counselors.json
  src/resolvers/Counselor.js
  src/resolvers/Counselor.test.js
  src/resolvers/allCounselors.js
  src/resolvers/allCounselors.test.js
  src/resolvers/findCounselorById.js
  src/resolvers/findCounselorById.test.js
  src/resolvers/index.js
  src/resolvers/ready.js
  src/resolvers/ready.test.js
  src/resolvers/totalCounselors.js
  src/resolvers/totalCounselors.test.js
  src/server.js
  src/typeDefs.graphql
Labels: documentation, feature, graphql, integration-testing, unit-testing

#41 10 setup GitHub auth
  .babelrc
  README.MD
  features/github_authorization.feature
  features/step_definitions/GraphQL_Query_Steps.js
  features/support/world.js
  package-lock.json
  package.json
  src/data/counselors.json
  src/environment.js
  src/environment.test.js
  src/resolvers/githubAuthUrl.js
  src/resolvers/githubAuthUrl.test.js
  src/resolvers/index.js
  src/resolvers/index.test.js
  src/typeDefs.graphql
  webpack.config.js
Labels: graphql, security

#42 Improved descriptions
  src/typeDefs.graphql
Labels: documentation
